SETTINGS:
  connect: 5
  write: 5
  read: 5
  pool: 5
  allow:
    - 200
    - 301
    - 302
  thread: 100
  number: 50
  detail: false
  save: false
  proxy: false

HTTP:
  headers:
    User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:127.0) Gecko/20100101 Firefox/127.0"
  cookies: ""
  proxy:
    email: ""
    key: ""
    q: 'protocol=="socks5" && "Version:5 Method:No Authentication(0x00)" && country="CN"'
    url:
